baseURL = "https://michmatyc.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "MichMATYC"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "Conferences"
url = "https://michmatyc.netlify.com/conf/"
weight = 3
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
