baseURL = "https://michmatyc.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "MichMATYC"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "Other Information"
url = "https://michmatyc.netlify.com/other-information/"
weight = 6
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
