baseURL = "https://michmatyc.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "MichMATYC"
summaryLength = 20
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "MiTEAM Program"
url = "https://michmatyc.netlify.com/miteam/"
weight = 6
[[menu.main]]
name = "Conferences"
url = "https://michmatyc.netlify.com/conf/"
weight = 4
[[menu.main]]
name = "About"
url = "https://michmatyc.netlify.com/about/"
weight = 1
[[menu.main]]
name = "Other Information"
url = "https://michmatyc.netlify.com/other-information/"
weight = 8
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
