baseURL = "https://michmatyc.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "MichMATYC"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
