baseURL = "https://michmatyc.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "MichMATYC"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "Conferences"
weight = 4
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
