baseURL = "https://michmatyc.org/"
languageCode = "en-us"
summaryLength = 20
theme = "hyde"
title = "MichMATYC"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "MiTEAM Program"
url = "https://michmatyc.org/miteam/"
weight = 6
[[menu.main]]
name = "Conferences"
url = "https://michmatyc.netlify.com/conf/"
weight = 4
[[menu.main]]
name = "About"
url = "https://michmatyc.org/about/"
weight = 1
[[menu.main]]
name = "Other Information"
url = "https://michmatyc.org/other-information/"
weight = 8
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
