---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/announcements
  label: Announcements
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*"
  templates:
  - page
- type: document
  path: config.toml
  label: Site Configuration
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
